version: "3.8"
services:
  backend:
    build:
      args:
        - NODE_ENV=production
      context: app/backend
    command: npm run start
    environment:
      - NODE_ENV=production
      - PORT=80
    ports:
      - 80:80
